import { readdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
const root=resolve(process.env.REDESIGN_EVIDENCE_DIR||'data/redesign-evidence');
const before=new Set(await readdir(root+'/before'));
const after=new Set(await readdir(root+'/after'));
const admin=new Set(await readdir(root+'/admin').catch(()=>[]));
const afterPath=file=>after.has(file)?'after/'+file:file.startsWith('admin-runners-')&&admin.has(file.replace('admin-runners-','workers-'))?'admin/'+file.replace('admin-runners-','workers-'):null;
const old=JSON.parse(await readFile(root+'/before/manifest.json','utf8'));
const meta=new Map(old.captures.map(row=>[row.file,row]));
const current=JSON.parse(await readFile(root+'/after/workbench-matrix.json','utf8').catch(()=>'{"captures":[]}'));
const currentMeta=new Map(current.captures.map(row=>[row.file,row]));
const pairs=[...before].filter(file=>afterPath(file)&&/^.+-\d+x\d+-(light|dark)\.png$/.test(file)).sort().map(file=>{
const [,state,width,height,theme]=file.match(/^(.+)-(\d+)x(\d+)-(light|dark)\.png$/);
return {file,afterPath:afterPath(file),state,width:Number(width),height:Number(height),theme,beforeKind:meta.get(file)?.kind||'Secondary page body before propagation; global shell already redesigned',afterKind:currentMeta.get(file)?.kind||(state.startsWith('page-')?'Real isolated CRUD test records; no model execution':state==='settings'?'Real saved settings and connection validation':state==='admin-runners'?'Real isolated Runner cluster':'See operation evidence')};
});
const labels={empty:'新任务空态',executing:'执行过程',approval:'等待审批',result:'完成与成果',error:'错误状态',recovery:'恢复后',settings:'设置','admin-runners':'Runner 管理','long-content':'长内容压力夹具','page-projects':'项目','page-experts':'专家','page-automations':'自动化','page-memory':'记忆','page-search':'搜索'};
const html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Pig Agent · 重设计前后证据</title><style>
*{box-sizing:border-box}body{margin:0;background:#f5f6f6;color:#202622;font:15px/1.65 system-ui,-apple-system,sans-serif}header,main{max-width:1680px;margin:auto;padding:28px}h1{margin:0 0 12px;font-size:25px}p{margin:8px 0;color:#55615a}a{color:#206148}nav{display:flex;gap:20px;flex-wrap:wrap;margin:18px 0}label{display:flex;gap:8px;align-items:center}select{font:inherit;border:1px solid #c9d0cc;border-radius:5px;padding:7px;background:white}.notice{border-left:3px solid #b57d24;background:#fff9e9;padding:12px 18px;margin-top:18px;font-size:13px}.pair{margin-bottom:34px;border:1px solid #d4dad6;border-radius:8px;overflow:hidden;background:white}.pair h2{font-size:18px;margin:0;padding:16px 20px;border-bottom:1px solid #e2e6e3}.pair .meta{font-size:12px;padding:8px 20px;color:#69766d}.compare{display:grid;grid-template-columns:1fr 1fr;gap:1px;background:#d4dad6}.shot{padding:12px;background:#eef0ee;min-width:0}.shot b{display:block;margin-bottom:8px;font-size:13px}.shot a{display:block}.shot img{display:block;width:100%;height:auto;background:white}.shot.mobile img{max-width:390px;margin:auto}.empty{padding:40px;text-align:center;background:white;border:1px solid #d4dad6}footer{padding:0 28px 30px;text-align:center;color:#69766d;font-size:12px}@media(max-width:760px){header,main{padding:18px}.compare{grid-template-columns:1fr}.pair h2{font-size:16px}}
</style><header><h1>Pig Agent · 重设计前后证据</h1><p>逐张对照同尺寸截图。点击图片可打开原图；视觉对照与功能证据分别记录。</p><nav><a href="before/manifest.json">原版核心截图元信息</a><a href="after/workbench-matrix.json">改版后核心截图元信息</a><a href="after/settings-check.json">设置实际操作</a><a href="after/pages-flow.json">页面实际操作</a><a href="artifact-source.json">成果来源验证</a><a href="before/README.md">基线说明与边界</a></nav><div class="notice">任务列表、长 Markdown 等压力内容明确使用 UI 夹具；审批、成果、下载使用真实 mock 容器。基线 executing 在连续截图期间可能进入等待审批。旧管理端没有深色模式。page-* 基线仅表示旧页面内容，外层导航已经重设计。截图本身不证明可靠性或生产容量。</div><nav><label>尺寸<select id="size"><option value="1440x900">1440 × 900</option><option value="1280x800">1280 × 800</option><option value="390x844">390 × 844</option></select></label><label>主题<select id="theme"><option value="light">浅色</option><option value="dark">深色</option></select></label><label>页面<select id="state"><option value="all">全部可配对页面</option></select></label></nav></header><main id="pairs"></main><footer>生成时间 ${new Date().toISOString()} · ${pairs.length} 组实际存在的同尺寸图片，不用近似尺寸替代缺失证据。</footer><script>
const pairs=${JSON.stringify(pairs)},labels=${JSON.stringify(labels)};const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
for(const key of [...new Set(pairs.map(p=>p.state))]){const o=document.createElement('option');o.value=key;o.textContent=labels[key]||key;document.querySelector('#state').append(o)}
function render(){const size=document.querySelector('#size').value,theme=document.querySelector('#theme').value,state=document.querySelector('#state').value;const selected=pairs.filter(p=>p.width+'x'+p.height===size&&p.theme===theme&&(state==='all'||p.state===state));document.querySelector('#pairs').innerHTML=selected.length?selected.map(p=>'<section class="pair"><h2>'+escape(labels[p.state]||p.state)+' · '+p.width+' × '+p.height+' · '+(p.theme==='dark'?'深色':'浅色')+'</h2><div class="meta">基线类型：'+escape(p.beforeKind)+'<br>改版后类型：'+escape(p.afterKind)+'</div><div class="compare">'+['before','after'].map(side=>'<div class="shot '+(p.width===390?'mobile':'')+'"><b>'+(side==='before'?'改版前':'改版后')+'</b><a href="'+escape(side==='after'?p.afterPath:'before/'+p.file)+'" target="_blank"><img loading="lazy" alt="'+escape(p.state+' '+side)+'" src="'+escape(side==='after'?p.afterPath:'before/'+p.file)+'"></a></div>').join('')+'</div></section>').join(''):'<div class="empty">这个筛选条件尚无完整配对截图。重新生成索引前不会把缺失证据当作已完成。</div>'}for(const select of document.querySelectorAll('select'))select.addEventListener('change',render);render();
</script></html>`;
await writeFile(root+'/index.html',html);await writeFile(root+'/paired-index.json',JSON.stringify({at:new Date().toISOString(),pairs},null,2));console.log(JSON.stringify({index:root+'/index.html',pairs:pairs.length}));
