import{resolve}from'node:path';
import{chromium,expect}from'@playwright/test';import{mkdir,writeFile}from'node:fs/promises';
const base='http://127.0.0.1:8799',out='data/redesign-evidence/after';await mkdir(out,{recursive:true});const browser=await chromium.launch({channel:'chrome'});const page=await browser.newPage({viewport:{width:1440,height:900}});const errors=[],checks=[],captures=[];page.on('pageerror',e=>errors.push(e.message));
const configured=await fetch(base+'/api/settings').then(r=>r.json());if(resolve(configured.workspaceRoot)!==resolve('data/redesign-local/workspace')){await browser.close();throw Error('Expected isolated data/redesign-local/workspace; refusing fixture creation');}
const mark=Date.now().toString(36);const names={项目:'[验收] 发布准备 '+mark,专家:'[验收] 交付审查 '+mark,自动化:'[验收] 手动检查 '+mark,记忆:'[验收] 所有发布必须核对成果来源 '+mark};
async function navigate(name){await page.setViewportSize({width:1440,height:900});await page.goto(base);await page.getByRole('navigation').first().getByRole('button',{name,exact:true}).click();await page.locator('.resource-header').waitFor();}
async function shot(state){for(const theme of['light','dark'])for(const[width,height]of[[1440,900],[1280,800],[390,844]]){await page.setViewportSize({width,height});await page.evaluate(t=>{localStorage.setItem('pig-agent.theme',t);document.documentElement.dataset.theme=t;document.documentElement.style.colorScheme=t;window.dispatchEvent(new StorageEvent('storage',{key:'pig-agent.theme',newValue:t}));},theme);await page.waitForTimeout(80);const file=`${state}-${width}x${height}-${theme}.png`;await page.screenshot({path:out+'/'+file});const metrics=await page.evaluate(()=>({viewport:innerWidth,scrollWidth:document.documentElement.scrollWidth,contentWidth:document.querySelector('.resource-content')?.getBoundingClientRect().width}));if(metrics.scrollWidth>width)throw Error('Overflow '+file);captures.push({state,file,width,height,theme,metrics});}await page.setViewportSize({width:1440,height:900});}
try{
 for(const name of['项目','专家','自动化','记忆']){
  await navigate(name);await page.locator('.resource-header button').click();const catalog=page.getByRole('dialog',{name:name+'目录',exact:true});await expect(catalog).toBeVisible();
  if(name==='项目'){await catalog.getByPlaceholder('新项目名称').fill(names[name]);await catalog.getByRole('button',{name:'新建项目',exact:true}).click();}
  if(name==='专家'){await catalog.getByPlaceholder('新专家名称').fill(names[name]);await catalog.getByPlaceholder('指令（会注入系统提示）').fill('先检查交付成果与执行来源，再逐项复核要求。');await catalog.getByRole('button',{name:'新建专家',exact:true}).click();}
  if(name==='自动化'){await catalog.getByPlaceholder('新自动化名称').fill(names[name]);await catalog.getByPlaceholder('每次运行的提示词').fill('仅用于页面验收，不运行模型。');await catalog.getByRole('button',{name:'新建自动化',exact:true}).click();}
  if(name==='记忆'){await catalog.getByPlaceholder('钉住一条事实，例如：默认用 DeepSeek').fill(names[name]);await catalog.getByRole('button',{name:'钉住笔记',exact:true}).click();}
  await expect(catalog).not.toBeVisible({timeout:10000});checks.push(name+' real API create and selected detail');
  if(name==='项目'){await page.getByPlaceholder('新待办').fill('核对来源与下载内容');await page.getByPlaceholder('新待办').press('Enter');await expect(page.getByText('核对来源与下载内容',{exact:true})).toBeVisible();checks.push('project todo created');}
  await shot('page-'+({'项目':'projects','专家':'experts','自动化':'automations','记忆':'memory'}[name]));
  await page.locator('.resource-header button').click();await catalog.getByLabel('搜索'+name).fill(mark);await expect(catalog.getByRole('button',{name:new RegExp(mark)}).first()).toBeVisible();await page.setViewportSize({width:390,height:844});await page.screenshot({path:out+'/catalog-'+({'项目':'projects','专家':'experts','自动化':'automations','记忆':'memory'}[name])+'-390x844-dark.png'});await catalog.getByRole('button',{name:new RegExp(mark)}).first().click();await expect(catalog).not.toBeVisible();checks.push(name+' catalog search and mobile selection');
 }
 await navigate('搜索');await page.getByLabel('搜索所有记录').fill(mark);await expect(page.getByRole('status')).not.toContainText('正在搜索',{timeout:10000});await expect(page.locator('.resource-search-results strong').filter({hasText:names.项目}).first()).toBeVisible();await shot('page-search');await page.locator('.resource-search-results strong').filter({hasText:names.项目}).first().click();await expect(page.locator('.resource-content h2')).toHaveText(names.项目);checks.push('search actual records and open project');
 await writeFile(out+'/pages-flow.json',JSON.stringify({at:new Date().toISOString(),workspaceRoot:configured.workspaceRoot,checks,captures,errors,fixtureNames:names},null,2));if(errors.length)throw Error(errors.join('\n'));console.log(JSON.stringify({ok:true,checks,screenshots:captures.length}));
}catch(e){await page.screenshot({path:out+'/pages-failure.png'});console.error(String(e.message).split('\n').slice(0,8).join('\n'));process.exitCode=1;}finally{await browser.close()}
